### ISSUE TITLE
Failed tests in SMTLIBParserTest when executing "gradlew build" command.

### ISSUE THREAD

**Issue by XYHyouKa** [tudo-aqua/jconstraints#25]
Prompt message is as below:
```
> Task :jconstraints-core:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jconstraints-core:test'.
> There were failing tests. See the report at: file:///D:/AQUA/jconstrain
ts/jconstraints-core/build/reports/tests/test/index.html
```
And concrete message in index.html is:
```
tjava.lang.UnsupportedOperationException: String bvshr cannot be resolved to jConstraintsOperator
	at gov.nasa.jpf.constraints.expressions.ExpressionOperator.fromString(ExpressionOperator.java:64)
	at gov.nasa.jpf.constraints.smtlibUtility.parser.SMTLIBParser.processFunctionExpression(SMTLIBParser.java:528)
	at gov.nasa.jpf.constraints.smtlibUtility.parser.SMTLIBParser.processArgument(SMTLIBParser.java:273)
	at gov.nasa.jpf.constraints.smtlibUtility.parser.SMTLIBParser.processFunctionExpression(SMTLIBParser.java:480)
	at gov.nasa.jpf.constraints.smtlibUtility.parser.SMTLIBParser.processExpression(SMTLIBParser.java:380)
	at gov.nasa.jpf.constraints.smtlibUtility.parser.SMTLIBParser.processAssert(SMTLIBParser.java:187)
	at gov.nasa.jpf.constraints.smtlibUtility.parser.SMTLIBParser.parseSMTProgram(SMTLIBParser.java:164)
	at gov.nasa.jpf.constraints.smtlibUtility.parser.SMTLIBParserTest.debugging(SMTLIBParserTest.java:298)
......
```
It seems like a JUnit test case triggers an unhandled exception, but `bvshr` should be a valid operator in fact.

This is my jre:
java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)

Thanks.

**Comment by XYHyouKa** [comment]
Further information, `BitvectorOperator.fromString` will be called insides `ExpressionOperator.fromString`, to handle bitvector operation. There is no case named `bvshr` in `BitvectorOperator`, however. Only `bvashr` and `bvlshr`, corresponding to arithmetic shift right and logical shift right (signed shift right and unsigned shift right).
Should add support for default `bvshr` in `BitvectorOperator`? Or the JUnit test case needs to be modified?

**Comment by mmuesly** [comment]
Hi @XYHyouka,

the failing test case is a leftover from previous debugging. I removed it. SMTLib only supports `bvashr` and `bvlshr` as you said. I am still fixing the CI pipeline, but I hope you can continue with your use case already. Feel free to get back to me, if you have any further questions.

**Comment by XYHyouKa** [comment]
@mmuesly OK, I pull the newest version and it works. But a new problem occurs,
'java.lang.UnsatisfiedLinkError: Unsupported operating system: Windows 7'
relevant codes:
```
public static OS identify() {
    String var0 = System.getProperty("os.name");
    if (!var0.startsWith("Darwin") && !var0.startsWith("Mac")) {
        if (var0.startsWith("Linux")) {
            return UNIX;
        } else {
            throw new UnsatisfiedLinkError("Unsupported operating system: " + var0);
        }
    } else {
        return OSX;
    }
}
```
I also check the `cvc5-turnkey-1.0.2.jar` file, there is no support for Windows .dll.
Can I build jConstraints under Windows OS in another way?

**Comment by mmuesly** [comment]
There are no windows binaries provided for cvc5 in our turnkey artifacts. Major parts of jConstraints will not work and we do not really support running it on windows. You should be able to build the `jconstraints-core` project and `jconstraints-z3` project from within the subfolders. The command is `../gradlew build`. These libraries together should work on windows. Does this help?

**Comment by XYHyouKa** [comment]
I tried as you said, building `core` and `z3` independently is successful. After that I also tried to build under Linux (Ubuntu), there are 2 test case failed.
```
StringSupportTest > conversionTest() FAILED
    java.lang.IllegalArgumentException: Cannot parse the variable of the model
        at io.github.tudoaqua.jconstraints.cvc5.CVC5Solver.getModel(CVC5Solver.java:143)
        at io.github.tudoaqua.jconstraints.cvc5.CVC5Solver.solve(CVC5Solver.java:194)
        at io.github.tudoaqua.jconstraints.cvc5.expressions.StringSupportTest.conversionTest(StringSupportTest.java:218)

SMTLibSnippetsParsingTest > testUsedInMulti() FAILED
    java.lang.IllegalArgumentException: Cannot parse the variable of the model
        at io.github.tudoaqua.jconstraints.cvc5.CVC5Solver.getModel(CVC5Solver.java:143)
        at io.github.tudoaqua.jconstraints.cvc5.CVC5Solver.solve(CVC5Solver.java:194)
        at io.github.tudoaqua.jconstraints.cvc5.smtlibBenchmarks.SMTLibSnippetsParsingTest.testUsedInMulti(SMTLibSnippetsParsingTest.java:50)
```

**Comment by mmuesly** [comment]
Sorry, @XYHyouka I have not had a chance to take a look into the test today, but will give it a shot tomorrow.

In the meantime, you can run `./gradlew publishToMavenLocal` and just use the library. If the other tests passes, the majority of JConstraints should work correctly on your linux system.
