### ISSUE TITLE
How to create a z3 solver?

### ISSUE THREAD

**Issue by syheliel** [tudo-aqua/jconstraints#26]
Here is my code:
```
@Test
public void aa(){
        ConstraintSolverFactory.createSolver("z3");
}
```
The stacktrace is:
```
gov.nasa.jpf.constraints.solvers.SolverNotFoundExcpetion: Specified solver could not be found
 at gov.nasa.jpf.constraints.solvers.ConstraintSolverFactory.createSolver(ConstraintSolverFactory.java:108)
 at gov.nasa.jpf.constraints.solvers.ConstraintSolverFactory.createSolver(ConstraintSolverFactory.java:148)
 ```
The pom.xml is:
```
  <dependency>
  <groupId>tools.aqua</groupId>
  <artifactId>jconstraints-core</artifactId>
  <version>0.9.9</version>
  </dependency>
```

**Comment by syheliel** [comment]
Solved, I need to add this into `pom.xml`:
```
   <dependency>
     <groupId>tools.aqua</groupId>
     <artifactId>jconstraints-z3</artifactId>
     <version>0.9.9</version>
   </dependency>
```
